if(NOT TARGET SDL2::SDL2_gfx)
    find_path(SDL2_GFX_INCLUDE_DIR "SDL2_gfxPrimitives.h")
    find_library(SDL2_GFX_LIB "SDL2_gfx")

    get_filename_component(SLD2_GFX_LIB_DIR ${SDL2_GFX_LIB} DIRECTORY)

    add_library(SDL2::SDL2_gfx SHARED IMPORTED)
    set_target_properties(SDL2::SDL2_gfx
        PROPERTIES
            INTERFACE_INCLUDE_DIRECTORIES "${SDL2_GFX_INCLUDE_DIR}"
            IMPORTED_LINK_INTERFACE_LANGUAGES "C"
            IMPORTED_LOCATION "${SLD2_GFX_LIB_DIR}/${CMAKE_SHARED_LIBRARY_PREFIX}SDL2_gfx${CMAKE_SHARED_LIBRARY_SUFFIX}"
            INTERFACE_LINK_LIBRARIES "${SDL2_EXTRA_LINK_FLAGS}"
    )
endif()