if(NOT TARGET SDL2::SDL2_ttf)
    find_path(SDL2_TTF_INCLUDE_DIR "SDL2/SDL_ttf.h")
    find_library(SDL2_TTF_LIB "SDL2_ttf")

    get_filename_component(SLD2_TTF_LIB_DIR ${SDL2_TTF_LIB} DIRECTORY)

    add_library(SDL2::SDL2_ttf SHARED IMPORTED)
    set_target_properties(SDL2::SDL2_ttf
        PROPERTIES
            INTERFACE_INCLUDE_DIRECTORIES "${SDL2_TTF_INCLUDE_DIR}"
            IMPORTED_LINK_INTERFACE_LANGUAGES "C"
            IMPORTED_LOCATION "${SLD2_TTF_LIB_DIR}/${CMAKE_SHARED_LIBRARY_PREFIX}SDL2_ttf${CMAKE_SHARED_LIBRARY_SUFFIX}"
            INTERFACE_LINK_LIBRARIES "${SDL2_EXTRA_LINK_FLAGS}"
    )
endif()