if(NOT TARGET SDL2::SDL2)
    find_path(SDL2_INCLUDE_DIR "SDL2/SDL.h")
    find_library(SDL2_LIB "SDL2")

    get_filename_component(SLD2_LIB_DIR ${SDL2_LIB} DIRECTORY)

    add_library(SDL2::SDL2 SHARED IMPORTED)
    set_target_properties(SDL2::SDL2
        PROPERTIES
            INTERFACE_INCLUDE_DIRECTORIES "${SDL2_INCLUDE_DIR}"
            IMPORTED_LINK_INTERFACE_LANGUAGES "C"
            IMPORTED_LOCATION "${SLD2_LIB_DIR}/${CMAKE_SHARED_LIBRARY_PREFIX}SDL2${CMAKE_SHARED_LIBRARY_SUFFIX}"
            INTERFACE_LINK_LIBRARIES "${SDL2_EXTRA_LINK_FLAGS}"
    )

    add_library(SDL2::SDL2main SHARED IMPORTED)
    set_target_properties(SDL2::SDL2main
        PROPERTIES
            INTERFACE_INCLUDE_DIRECTORIES "${SDL2_INCLUDE_DIR}"
            IMPORTED_LINK_INTERFACE_LANGUAGES "C"
            IMPORTED_LOCATION "${SLD2_LIB_DIR}/${CMAKE_SHARED_LIBRARY_PREFIX}SDL2main${CMAKE_SHARED_LIBRARY_SUFFIX}"
            INTERFACE_LINK_LIBRARIES "${SDL2_EXTRA_LINK_FLAGS}"
    )
endif()
